# -- MySQL Script generated by MySQL Workbench
# -- ned 20 dec 2020 20:53:12
# -- Model: New Model    Version: 1.0
# -- MySQL Workbench Forward Engineering
#
# SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
# SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
# SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
#
# -- -----------------------------------------------------
# -- Schema mydb
# -- -----------------------------------------------------
#
# -- -----------------------------------------------------
# -- Schema mydb
# -- -----------------------------------------------------
# drop database if exists mydb;
# CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovenian_ci ;
 USE `mydb` ;
#
# -- -----------------------------------------------------
# -- Table `mydb`.`administrator`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`administrator` (
#                                                       `admin_id` INT NOT NULL AUTO_INCREMENT,
#                                                       `name` VARCHAR(45) NOT NULL,
#                                                       `surname` VARCHAR(45) NOT NULL,
#                                                       `email` VARCHAR(45) NOT NULL,
#                                                       `password` VARCHAR(250) NOT NULL,
#                                                       PRIMARY KEY (`admin_id`),
#                                                       UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC) VISIBLE,
#                                                       UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`status`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`status` (
#                                                `status_id` INT NOT NULL,
#                                                `name` VARCHAR(45) NULL,
#                                                PRIMARY KEY (`status_id`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`prodajalec`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`prodajalec` (
#                                                    `prodajalec_id` INT NOT NULL AUTO_INCREMENT,
#                                                    `name` VARCHAR(45) NOT NULL,
#                                                    `surname` VARCHAR(45) NOT NULL,
#                                                    `email` VARCHAR(45) NOT NULL,
#                                                    `password` VARCHAR(250) NOT NULL,
#                                                    `status_status_id` INT NOT NULL,
#                                                    PRIMARY KEY (`prodajalec_id`),
#                                                    UNIQUE INDEX `prodajalec_id_UNIQUE` (`prodajalec_id` ASC) VISIBLE,
#                                                    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
#                                                    INDEX `fk_prodajalec_status1_idx` (`status_status_id` ASC) VISIBLE,
#                                                    CONSTRAINT `fk_prodajalec_status1`
#                                                        FOREIGN KEY (`status_status_id`)
#                                                            REFERENCES `mydb`.`status` (`status_id`)
#                                                            ON DELETE NO ACTION
#                                                            ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`naslov`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`naslov` (
#                                                `postNum` INT NOT NULL,
#                                                `postName` VARCHAR(45) NOT NULL,
#                                                PRIMARY KEY (`postNum`))
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`stranka`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`stranka` (
#                                                 `stranka_id` INT NOT NULL AUTO_INCREMENT,
#                                                 `name` VARCHAR(45) NOT NULL,
#                                                 `surname` VARCHAR(45) NOT NULL,
#                                                 `email` VARCHAR(45) NOT NULL,
#                                                 `password` VARCHAR(250) NOT NULL,
#                                                 `naslov_postNum` INT NOT NULL,
#                                                 `status_status_id` INT NOT NULL,
#                                                 `street` VARCHAR(45) NOT NULL,
#                                                 PRIMARY KEY (`stranka_id`),
#                                                 UNIQUE INDEX `stranka_id_UNIQUE` (`stranka_id` ASC) VISIBLE,
#                                                 UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
#                                                 INDEX `fk_stranka_naslov1_idx` (`naslov_postNum` ASC) VISIBLE,
#                                                 INDEX `fk_stranka_status1_idx` (`status_status_id` ASC) VISIBLE,
#                                                 CONSTRAINT `fk_stranka_naslov1`
#                                                     FOREIGN KEY (`naslov_postNum`)
#                                                         REFERENCES `mydb`.`naslov` (`postNum`)
#                                                         ON DELETE NO ACTION
#                                                         ON UPDATE NO ACTION,
#                                                 CONSTRAINT `fk_stranka_status1`
#                                                     FOREIGN KEY (`status_status_id`)
#                                                         REFERENCES `mydb`.`status` (`status_id`)
#                                                         ON DELETE NO ACTION
#                                                         ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`produkt`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`produkt` (
#                                                 `product_id` INT NOT NULL AUTO_INCREMENT,
#                                                 `name` VARCHAR(45) NOT NULL,
#                                                 `price` VARCHAR(45) NOT NULL,
#                                                 `describtion` VARCHAR(200) NULL,
#                                                 `status_status_id` INT NOT NULL,
#                                                 PRIMARY KEY (`product_id`),
#                                                 UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
#                                                 INDEX `fk_produkt_status1_idx` (`status_status_id` ASC) VISIBLE,
#                                                 CONSTRAINT `fk_produkt_status1`
#                                                     FOREIGN KEY (`status_status_id`)
#                                                         REFERENCES `mydb`.`status` (`status_id`)
#                                                         ON DELETE NO ACTION
#                                                         ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`category`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`category` (
#                                                  `category_id` INT NOT NULL,
#                                                  `name` VARCHAR(255) NOT NULL,
#                                                  PRIMARY KEY (`category_id`));
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`user`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`user` (
#                                              `username` VARCHAR(16) NOT NULL,
#                                              `email` VARCHAR(255) NULL,
#                                              `password` VARCHAR(32) NOT NULL,
#                                              `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`timestamps`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
#                                                    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
#                                                    `update_time` TIMESTAMP NULL);
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`narocilo`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`narocilo` (
#                                                  `order_id` INT NOT NULL AUTO_INCREMENT,
#                                                  `created` VARCHAR(45) NOT NULL,
#                                                  `status_status_id` INT NOT NULL,
#                                                  `stranka_stranka_id` INT NOT NULL,
#                                                  PRIMARY KEY (`order_id`),
#                                                  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
#                                                  INDEX `fk_narocilo_status1_idx` (`status_status_id` ASC) VISIBLE,
#                                                  INDEX `fk_narocilo_stranka1_idx` (`stranka_stranka_id` ASC) VISIBLE,
#                                                  CONSTRAINT `fk_narocilo_status1`
#                                                      FOREIGN KEY (`status_status_id`)
#                                                          REFERENCES `mydb`.`status` (`status_id`)
#                                                          ON DELETE NO ACTION
#                                                          ON UPDATE NO ACTION,
#                                                  CONSTRAINT `fk_narocilo_stranka1`
#                                                      FOREIGN KEY (`stranka_stranka_id`)
#                                                          REFERENCES `mydb`.`stranka` (`stranka_id`)
#                                                          ON DELETE NO ACTION
#                                                          ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# -- -----------------------------------------------------
# -- Table `mydb`.`narocilo_has_produkt`
# -- -----------------------------------------------------
# CREATE TABLE IF NOT EXISTS `mydb`.`narocilo_has_produkt` (
#                                                              `narocilo_order_id` INT NOT NULL,
#                                                              `produkt_product_id` INT NOT NULL,
#                                                              `kolicina` INT NOT NULL,
#                                                              PRIMARY KEY (`narocilo_order_id`, `produkt_product_id`),
#                                                              INDEX `fk_narocilo_has_produkt_produkt1_idx` (`produkt_product_id` ASC) VISIBLE,
#                                                              INDEX `fk_narocilo_has_produkt_narocilo1_idx` (`narocilo_order_id` ASC) VISIBLE,
#                                                              CONSTRAINT `fk_narocilo_has_produkt_narocilo1`
#                                                                  FOREIGN KEY (`narocilo_order_id`)
#                                                                      REFERENCES `mydb`.`narocilo` (`order_id`)
#                                                                      ON DELETE NO ACTION
#                                                                      ON UPDATE NO ACTION,
#                                                              CONSTRAINT `fk_narocilo_has_produkt_produkt1`
#                                                                  FOREIGN KEY (`produkt_product_id`)
#                                                                      REFERENCES `mydb`.`produkt` (`product_id`)
#                                                                      ON DELETE NO ACTION
#                                                                      ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;
#
#
# SET SQL_MODE=@OLD_SQL_MODE;
# SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
# SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO status (status_id, name) VALUES
(1, 'aktiven'),
(2, 'neaktiven'),
(3, 'neobdelano'),
(4, 'potrjeno'),
(5, 'zavrnjeno'),
(6, 'stornirano');

INSERT INTO naslov (postNum, postName) VALUES
(1000, 'Ljubljana');

INSERT INTO `produkt` (`product_id`, `name`, `price`, `describtion`, `status_status_id`) VALUES
(1, 'produkt1', 100, 'produkt stevilka ena', 1),
(2, 'produkt2', 10, 'produkt stevilka stiri', 1),
(3, 'produkt3', 150, 'produkt stevilka tri', 1),
(4, 'produkt4', 1000, 'produkt stevilka dva', 1);



